package e2ee

// Cross-implementation interop gate (W-G): proves the browser (TypeScript,
// @hpke/core on WebCrypto) and the Go/circl implementation are byte-compatible
// in BOTH directions. The committed fixtures in testdata/ are the shared
// oracle:
//
//   - interop_go_to_ts_*.json  — generated HERE (Go SetupS / Go encrypt),
//     opened by the browser (pagnet-web vitest).
//   - interop_ts_to_go_*.json  — generated by the browser (TS seal / TS
//     encrypt), opened HERE (Go SetupR / Go decrypt).
//
// The generator is idempotent: it skips when the Go->TS fixtures already
// exist (they are committed), so CI only runs the verifier. Run it once to
// (re)generate: `go test ./e2ee -run TestInteropGenerateGoFixtures -v` after
// deleting the committed Go->TS fixtures.

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/cloudflare/circl/hpke"
)

const interopSuite = "X25519_HKDF_SHA256/HKDF_SHA256/AES_256_GCM"

// genX25519 draws a fresh X25519 keypair (raw 32-byte pub/priv). The fixtures
// are committed, so the (random) keys are stable once generated.
func genX25519(t *testing.T) (pub, priv []byte) {
	t.Helper()
	pkR, skR, err := hpke.KEM_X25519_HKDF_SHA256.Scheme().GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	pub, err = pkR.MarshalBinary()
	if err != nil {
		t.Fatalf("marshal pub: %v", err)
	}
	priv, err = skR.MarshalBinary()
	if err != nil {
		t.Fatalf("marshal priv: %v", err)
	}
	return pub, priv
}

func b64(t *testing.T, b []byte) string {
	t.Helper()
	return base64.StdEncoding.EncodeToString(b)
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex decode: %v", err)
	}
	return b
}

// sealAESGCM is the stdlib AES-256-GCM seal (ct||tag) under a CEK with AAD.
func sealAESGCM(t *testing.T, cek, nonce, pt, aad []byte) []byte {
	t.Helper()
	block, err := aes.NewCipher(cek)
	if err != nil {
		t.Fatalf("aes.NewCipher: %v", err)
	}
	aead, _ := cipher.NewGCM(block)
	return aead.Seal(nil, nonce, pt, aad)
}

func openAESGCM(t *testing.T, cek, nonce, ct, aad []byte) []byte {
	t.Helper()
	block, err := aes.NewCipher(cek)
	if err != nil {
		t.Fatalf("aes.NewCipher: %v", err)
	}
	aead, _ := cipher.NewGCM(block)
	pt, err := aead.Open(nil, nonce, ct, aad)
	if err != nil {
		t.Fatalf("gcm open: %v", err)
	}
	return pt
}

// --- the Go -> TS fixtures (generated here, opened by the browser) ---------

type interopHPKEFixture struct {
	Version       int    `json:"version"`
	Direction     string `json:"direction"`
	Suite         string `json:"suite"`
	Info          string `json:"info"`
	NetworkID     string `json:"network_id"`
	SessionID     string `json:"session_id"`
	ObjectID      string `json:"object_id"`
	SessionAADB64 string `json:"session_aad_b64"`
	RecipientPub  string `json:"recipient_pub_b64"`
	RecipientPriv string `json:"recipient_priv_b64"`
	Enc           string `json:"enc_b64"`
	CT            string `json:"ct_b64"`
	CEKHex        string `json:"cek_hex"`
}

type interopPayloadFixture struct {
	Version       int                `json:"version"`
	Direction     string             `json:"direction"`
	Suite         string             `json:"suite"`
	Info          string             `json:"info"`
	NetworkID     string             `json:"network_id"`
	SessionID     string             `json:"session_id"`
	ObjectID      string             `json:"object_id"`
	SessionAADB64 string             `json:"session_aad_b64"`
	RecipientPub  string             `json:"recipient_pub_b64"`
	RecipientPriv string             `json:"recipient_priv_b64"`
	WrappedCEKEnc string             `json:"wrapped_cek_enc_b64"`
	WrappedCEKCT  string             `json:"wrapped_cek_ct_b64"`
	Envelope      EncryptedPayloadV1 `json:"envelope"`
	PayloadAAD    AAD                `json:"payload_aad"`
	Plaintext     string             `json:"plaintext"`
}

func writeJSON(t *testing.T, path string, v any) {
	t.Helper()
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func readJSON(t *testing.T, path string, v any) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if err := json.Unmarshal(b, v); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
}

// TestInteropGenerateGoFixtures generates the Go->TS interop fixtures (the
// browser opens them). Idempotent: skips when they already exist (committed).
func TestInteropGenerateGoFixtures(t *testing.T) {
	dir := filepath.Join("testdata")
	hpkePath := filepath.Join(dir, "interop_go_to_ts_hpke_v1.json")
	payloadPath := filepath.Join(dir, "interop_go_to_ts_payload_v1.json")
	if _, err := os.Stat(hpkePath); err == nil {
		t.Skip("Go->TS fixtures already exist (committed); delete them to regenerate")
	}

	const (
		networkID = "01900000-0000-7000-8000-000000000002"
		sessionID = "01900000-0000-7000-8000-000000000005"
		objectID  = "01900000-0000-7000-8000-000000000003"
	)
	// Recipient (browser) keypair — committed, so stable once generated.
	recvPub, recvPriv := genX25519(t)
	sessAAD := BrowserSessionAAD(networkID, sessionID, objectID)

	// (C) HPKE-only: Go SetupS seals the committed CEK to the browser.
	cek := unhex(t, VectorsV1[0].CEKHex)
	enc, ct, err := HPKEWrap(recvPub, []byte(HPKEInfoCekUnwrap), sessAAD, cek)
	if err != nil {
		t.Fatalf("HPKEWrap: %v", err)
	}
	writeJSON(t, hpkePath, interopHPKEFixture{
		Version: 1, Direction: "go_to_ts", Suite: interopSuite,
		Info:      HPKEInfoCekUnwrap,
		NetworkID: networkID, SessionID: sessionID, ObjectID: objectID,
		SessionAADB64: b64(t, sessAAD),
		RecipientPub:  b64(t, recvPub), RecipientPriv: b64(t, recvPriv),
		Enc: b64(t, enc), CT: b64(t, ct), CEKHex: VectorsV1[0].CEKHex,
	})

	// (B) full payload: Go encrypts (fresh CEK + nonce + AES-GCM) and the
	// daemon HPKE-wraps the CEK to the browser (info=cek-unwrap).
	var pcek [32]byte
	if _, err := rand.Read(pcek[:]); err != nil {
		t.Fatalf("rand cek: %v", err)
	}
	var nonce [12]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		t.Fatalf("rand nonce: %v", err)
	}
	plaintext := "interop-go-to-ts-payload-0123456789"
	payloadAAD := AAD{
		ProtocolVersion: 1,
		TenantID:        "01900000-0000-7000-8000-000000000001",
		NetworkID:       networkID,
		ObjectType:      ObjectTypeMessage,
		ObjectID:        objectID,
		Sender:          "alpha",
		Recipient:       "human",
		CreatedAt:       "2026-09-22T00:00:00Z",
		KeyEpochID:      "01900000-0000-7000-8000-000000000004",
	}
	ciphertext := sealAESGCM(t, pcek[:], nonce[:], []byte(plaintext), payloadAAD.CanonicalBytes())
	wenc, wct, err := HPKEWrap(recvPub, []byte(HPKEInfoCekUnwrap), sessAAD, pcek[:])
	if err != nil {
		t.Fatalf("HPKEWrap payload cek: %v", err)
	}
	env := EncryptedPayloadV1{
		Version:           EnvelopeVersion,
		CipherSuite:       CipherSuiteAES256GCM,
		KeyEpochID:        payloadAAD.KeyEpochID,
		Nonce:             b64(t, nonce[:]),
		Ciphertext:        b64(t, ciphertext),
		WrappedContentKey: b64(t, make([]byte, 12+32+16)), // opaque epoch re-wrap stand-in
		AADVersion:        AADVersion,
	}
	writeJSON(t, payloadPath, interopPayloadFixture{
		Version: 1, Direction: "go_to_ts", Suite: interopSuite,
		Info:      HPKEInfoCekUnwrap,
		NetworkID: networkID, SessionID: sessionID, ObjectID: objectID,
		SessionAADB64: b64(t, sessAAD),
		RecipientPub:  b64(t, recvPub), RecipientPriv: b64(t, recvPriv),
		WrappedCEKEnc: b64(t, wenc), WrappedCEKCT: b64(t, wct),
		Envelope: env, PayloadAAD: payloadAAD, Plaintext: plaintext,
	})
	t.Logf("wrote %s and %s", hpkePath, payloadPath)
}

// --- the TS -> Go fixtures (generated by the browser, opened here) ---------

// TestInteropVerifyTSFixtures opens the browser-generated fixtures with
// circl: (C) browser wrap -> Circl unwrap, and (B) browser encrypt -> Go
// decrypt. The fixtures are committed (generated by the pagnet-web vitest
// generator); when absent the test skips (the browser side has not run yet).
func TestInteropVerifyTSFixtures(t *testing.T) {
	dir := filepath.Join("testdata")
	hpkePath := filepath.Join(dir, "interop_ts_to_go_hpke_v1.json")
	payloadPath := filepath.Join(dir, "interop_ts_to_go_payload_v1.json")
	if _, err := os.Stat(hpkePath); err != nil {
		t.Skip("TS->Go fixtures not present (browser generator has not run / not committed)")
	}

	// (C) HPKE: browser wrap -> Circl unwrap.
	var hf interopHPKEFixture
	readJSON(t, hpkePath, &hf)
	if hf.Suite != interopSuite {
		t.Fatalf("fixture suite = %q, want %q", hf.Suite, interopSuite)
	}
	recvPriv, _ := base64.StdEncoding.DecodeString(hf.RecipientPriv)
	enc, _ := base64.StdEncoding.DecodeString(hf.Enc)
	ct, _ := base64.StdEncoding.DecodeString(hf.CT)
	sessAAD, _ := base64.StdEncoding.DecodeString(hf.SessionAADB64)
	cek, err := HPKEUnwrap(recvPriv, enc, []byte(hf.Info), sessAAD, ct)
	if err != nil {
		t.Fatalf("Circl unwrap of TS wrap: %v", err)
	}
	wantCEK := unhex(t, hf.CEKHex)
	if hex.EncodeToString(cek) != hf.CEKHex {
		t.Fatalf("Circl unwrap CEK = %x, want %s", cek, wantCEK)
	}

	// (B) full payload: browser encrypt -> Go decrypt.
	var pf interopPayloadFixture
	readJSON(t, payloadPath, &pf)
	if pf.Suite != interopSuite {
		t.Fatalf("payload fixture suite = %q, want %q", pf.Suite, interopSuite)
	}
	hostPriv, _ := base64.StdEncoding.DecodeString(pf.RecipientPriv)
	wenc, _ := base64.StdEncoding.DecodeString(pf.WrappedCEKEnc)
	wct, _ := base64.StdEncoding.DecodeString(pf.WrappedCEKCT)
	psessAAD, _ := base64.StdEncoding.DecodeString(pf.SessionAADB64)
	pcek, err := HPKEUnwrap(hostPriv, wenc, []byte(pf.Info), psessAAD, wct)
	if err != nil {
		t.Fatalf("Circl unwrap of TS payload CEK: %v", err)
	}
	envNonce, _ := base64.StdEncoding.DecodeString(pf.Envelope.Nonce)
	envCT, _ := base64.StdEncoding.DecodeString(pf.Envelope.Ciphertext)
	pt := openAESGCM(t, pcek, envNonce, envCT, pf.PayloadAAD.CanonicalBytes())
	if string(pt) != pf.Plaintext {
		t.Fatalf("Go decrypt plaintext = %q, want %q", pt, pf.Plaintext)
	}
}
