package federation

import (
	"context"
	"crypto/sha256"
	"sync"
	"time"
	"unicode/utf8"

	"github.com/pagnet-code/pagnet/fabric"
	"github.com/pagnet-code/pagnet/fabric/registry"
)

const admissionConfigurationID = "configuration-v1"

func newAdmissionLedger(ctx context.Context, c AdmissionConfig) (*AdmissionLedger, error) {
	if ctx == nil || ctx.Err() != nil {
		return nil, authError()
	}
	if c.Store == nil || c.Owner == nil || c.Protector == nil || c.Peers == nil || c.Policy == nil || !c.Limits.valid() || !c.Verification.valid() {
		return nil, authError()
	}
	ref := c.Protector.Reference()
	if !utf8.ValidString(ref.ID) || !utf8.ValidString(ref.Version) || len(ref.ID) == 0 || len(ref.ID) > 256 || len(ref.Version) == 0 || len(ref.Version) > 256 {
		return nil, protocolError()
	}
	root, e := c.Store.CurrentAuthorityIdentity(ctx)
	if e != nil {
		return nil, e
	}
	return &AdmissionLedger{config: c, root: root}, nil
}

// BootstrapAdmissionLedger initializes only the closed purpose's sealed quota
// record within an already genuine registry root. Missing retained replay state
// is never automatically regenerated by OpenAdmissionLedger.
func BootstrapAdmissionLedger(ctx context.Context, c AdmissionConfig) (*AdmissionLedger, error) {
	l, e := newAdmissionLedger(ctx, c)
	if e != nil {
		return nil, e
	}
	e = l.withOwner(ctx, func(ctx context.Context, tx *registry.AuthorityTx) error {
		if _, e := tx.Get(admissionKey(admissionConfigurationID)); !missingAuthority(e) {
			if e != nil {
				return e
			}
			return protocolError()
		}
		_, _, e := l.cas(tx, admissionConfigurationID, 0, admissionConfiguration{Version: admissionVersion, Key: c.Protector.Reference(), Limits: c.Limits, Verification: c.Verification})
		return e
	})
	if e != nil {
		return nil, e
	}
	return l, nil
}
func OpenAdmissionLedger(ctx context.Context, c AdmissionConfig) (*AdmissionLedger, error) {
	l, e := newAdmissionLedger(ctx, c)
	if e != nil {
		return nil, e
	}
	e = l.withOwner(ctx, func(ctx context.Context, tx *registry.AuthorityTx) error { _, _, e := l.configuration(tx); return e })
	if e != nil {
		return nil, e
	}
	return l, nil
}
func (l *AdmissionLedger) configuration(tx *registry.AuthorityTx) (registry.AuthorityRecord, admissionConfiguration, error) {
	var config admissionConfiguration
	row, e := l.read(tx, admissionConfigurationID, &config)
	if e != nil {
		return row, config, e
	}
	if config.Version != admissionVersion || config.Key != l.config.Protector.Reference() || config.Limits != l.config.Limits || config.Verification != l.config.Verification || config.Invocations > config.Limits.MaxInvocations || config.Bytes > config.Limits.MaxBytes {
		return row, config, authError()
	}
	return row, config, nil
}
func (l *AdmissionLedger) charge(tx *registry.AuthorityTx, row registry.AuthorityRecord, c admissionConfiguration, n uint64, fresh bool) error {
	if n > c.Limits.MaxBytes-c.Bytes || fresh && c.Invocations >= c.Limits.MaxInvocations {
		return fabric.NewError(fabric.ErrorCode("federation.capacity"), "Federation admission capacity exhausted")
	}
	c.Bytes += n
	if fresh {
		c.Invocations++
	}
	_, _, e := l.cas(tx, admissionConfigurationID, row.Revision, c)
	return e
}
func (l *AdmissionLedger) current(ctx context.Context, tx *registry.AuthorityTx, c Config, fn func(context.Context) error) error {
	c = cloneConfig(c)
	if c.SourceRole || !sameRoot(c.Local.Authority, l.root) || checkConfig(c) != nil {
		return authError()
	}
	var mu sync.Mutex
	active, called, invalid := true, false, false
	var result error
	e := l.config.Peers.WithCurrentTx(ctx, tx, c.Local, c.Remote, func(current context.Context) error {
		mu.Lock()
		defer mu.Unlock()
		if !active || called || current == nil || current.Err() != nil || ctx.Err() != nil {
			invalid = true
			return authError()
		}
		called = true
		result = fn(current)
		return result
	})
	mu.Lock()
	active = false
	valid := called && !invalid
	failure := result
	mu.Unlock()
	if e != nil {
		return e
	}
	if !valid {
		return authError()
	}
	return failure
}
func factsFor(c Config, b ForwardBundle, digest [32]byte) AdmissionFacts {
	f := b.Proof.Frame
	return AdmissionFacts{Principal: f.Principal, InvocationID: f.InvocationID, BundleDigest: digest, OriginalDigest: f.OriginalEnvelopeDigest, ForwardedDigest: f.ForwardedEnvelopeDigest, Source: c.Remote, Destination: c.Local, Target: f.Target, ExpectedRevision: f.ExpectedRevision}
}
func validAdmissionManifest(m admissionManifest) bool {
	expires, e := time.Parse(time.RFC3339Nano, m.ExpiresAt)
	if e != nil || expires.Location() != time.UTC || expires.Format(time.RFC3339Nano) != m.ExpiresAt {
		return false
	}
	if m.Deadline != "" {
		deadline, e := time.Parse(time.RFC3339Nano, m.Deadline)
		if e != nil || deadline.Location() != time.UTC || deadline.Format(time.RFC3339Nano) != m.Deadline || expires.After(deadline) {
			return false
		}
	}
	f := m.Facts
	if f.Principal.Ref == "" || f.Principal.Kind == "" || f.Principal.Issuer == "" || f.InvocationID == "" || f.OriginalDigest == ([32]byte{}) || f.ForwardedDigest == ([32]byte{}) || f.Target == nil || f.Target.String() == "" || f.ExpectedRevision == "" {
		return false
	}
	for _, p := range []PeerBinding{f.Source, f.Destination} {
		domain, e := fabric.DomainNamespace(p.Authority.PublicKey)
		if e != nil || domain != p.Authority.Namespace || p.Authority.StoreID == "" || p.Authority.KeyRevision == 0 || p.ExchangePublicKey == ([32]byte{}) || p.ExchangeKeyRevision == 0 || p.BindingDigest == ([32]byte{}) || p.ExpiresAt.IsZero() {
			return false
		}
	}
	if m.AttemptID != "" && (len(m.AttemptID) != len("attempt:")+64 || m.AttemptID[:len("attempt:")] != "attempt:") {
		return false
	}
	if m.Association != nil && (m.AttemptID == "" || !validAssociation(*m.Association)) {
		return false
	}
	if m.Cursor.Ordinal >= 0 && m.Association == nil {
		return false
	}
	return true
}
func (l *AdmissionLedger) manifest(tx *registry.AuthorityTx, key string) (registry.AuthorityRecord, admissionManifest, error) {
	var m admissionManifest
	row, e := l.read(tx, key, &m)
	if e != nil {
		return row, m, e
	}
	if !validAdmissionManifest(m) || m.Version != admissionVersion || m.Operation != fabric.OperationInvoke || m.BundleBytes == 0 || m.BundleBytes > MaxForwardBundleBytes || m.Chunks != uint32((int(m.BundleBytes)+admissionChunkBytes-1)/admissionChunkBytes) || invocationKey(m.Facts.Principal, m.Facts.InvocationID) != key || m.Facts.BundleDigest == ([32]byte{}) || m.Cursor.Ordinal < -1 || m.Cursor.Ordinal == -1 && m.Cursor.FrameDigest != ([32]byte{}) || m.Cursor.Ordinal >= 0 && m.Cursor.FrameDigest == ([32]byte{}) {
		return row, m, authError()
	}
	return row, m, nil
}
func (l *AdmissionLedger) bundle(tx *registry.AuthorityTx, key string, m admissionManifest) (ForwardBundle, error) {
	raw := make([]byte, 0, int(m.BundleBytes))
	defer func() { clear(raw[:cap(raw)]) }()
	for i := uint32(0); i < m.Chunks; i++ {
		row, part, e := l.readRaw(tx, chunkKey(key, i))
		if e != nil {
			return ForwardBundle{}, e
		}
		wanted := min(admissionChunkBytes, int(m.BundleBytes)-len(raw))
		if row.Revision != 1 || len(part) != wanted {
			clear(part)
			return ForwardBundle{}, authError()
		}
		raw = append(raw, part...)
		clear(part)
	}
	if len(raw) != int(m.BundleBytes) || sha256.Sum256(raw) != m.Facts.BundleDigest {
		return ForwardBundle{}, authError()
	}
	return DecodeForwardBundle(raw)
}
func (l *AdmissionLedger) authorize(ctx context.Context, tx *registry.AuthorityTx, action AdmissionAction, caller fabric.ExecutionContext, m admissionManifest) error {
	if caller.VerifyAuthenticated(l.root.Namespace) != nil {
		return authError()
	}
	// Operator delegation, when explicitly configured, is solely the injected
	// current policy's responsibility; core neither infers nor grants that access.
	return l.config.Policy.AuthorizeTx(ctx, tx, action, caller, cloneAdmissionFacts(m.Facts))
}

// Admit commits the exact original mapping before exposing an admission ACK.
// Existence never grants permission to repeat an uncertain endpoint effect.
func (l *AdmissionLedger) Admit(ctx context.Context, c Config, b ForwardBundle, caller fabric.ExecutionContext) (Admission, bool, error) {
	c = cloneConfig(c)
	if b.Proof.Frame.Operation != fabric.OperationInvoke {
		return Admission{}, false, protocolError()
	}
	raw, e := EncodeForwardBundle(b)
	if e != nil {
		return Admission{}, false, e
	}
	defer clear(raw)
	b, e = DecodeForwardBundle(raw)
	if e != nil {
		return Admission{}, false, e
	}
	digest := sha256.Sum256(raw)
	key := invocationKey(b.Proof.Frame.Principal, b.Proof.Frame.InvocationID)
	var accepted Admission
	fresh := false
	e = l.withOwner(ctx, func(ctx context.Context, tx *registry.AuthorityTx) error {
		return l.current(ctx, tx, c, func(current context.Context) error {
			counterRow, counter, e := l.configuration(tx)
			if e != nil {
				return e
			}
			_, m, e := l.manifest(tx, key)
			if e == nil {
				if m.Facts.BundleDigest != digest {
					return authError()
				}
				retained, e := l.bundle(tx, key, m)
				if e != nil {
					return e
				}
				if !sameRoot(m.Facts.Source.Authority, c.Remote.Authority) || !sameRoot(m.Facts.Destination.Authority, c.Local.Authority) {
					return authError()
				}
				originalPeers := c
				originalPeers.Remote = m.Facts.Source
				originalPeers.Local = m.Facts.Destination
				if e = verifyForwardContent(current, originalPeers, retained, l.config.Verification, true, func(context.Context, fabric.ExecutionContext) error { return nil }); e != nil {
					return e
				}
				if e = l.authorize(current, tx, ActionRead, caller, m); e != nil {
					return e
				}
				accepted = Admission{l, key, digest}
				return nil
			}
			if !missingAuthority(e) {
				return e
			}
			return verifyForwardContent(current, c, b, l.config.Verification, false, func(current context.Context, verified fabric.ExecutionContext) error {
				if caller.PrincipalView() != verified.PrincipalView() || !currentEnvelopeMatches(caller, b.Forwarded, l.root.Namespace) {
					return authError()
				}
				m = admissionManifest{Version: admissionVersion, Deadline: b.Proof.Frame.Deadline, ExpiresAt: b.Proof.Frame.ExpiresAt, Operation: b.Proof.Frame.Operation, Facts: factsFor(c, b, digest), BundleBytes: uint32(len(raw)), Chunks: uint32((len(raw) + admissionChunkBytes - 1) / admissionChunkBytes), Cursor: ConsumerCursor{Ordinal: -1}}
				if e = l.authorize(current, tx, ActionAdmit, caller, m); e != nil {
					return e
				}
				var size uint64
				for i := uint32(0); i < m.Chunks; i++ {
					start := int(i) * admissionChunkBytes
					end := min(start+admissionChunkBytes, len(raw))
					_, n, e := l.casRaw(tx, chunkKey(key, i), 0, raw[start:end])
					if e != nil {
						return e
					}
					size += uint64(n)
				}
				_, n, e := l.cas(tx, key, 0, m)
				if e != nil {
					return e
				}
				size += uint64(n)
				if e = l.charge(tx, counterRow, counter, size, true); e != nil {
					return e
				}
				accepted = Admission{l, key, digest}
				fresh = true
				return nil
			})
		})
	})
	if e != nil {
		return Admission{}, false, e
	}
	return accepted, fresh, nil
}

func currentEnvelopeMatches(c fabric.ExecutionContext, exact []byte, audience string) bool {
	_, e := c.DecodeVerifiedEnvelope(exact, audience)
	return e == nil
}

func cloneAdmissionFacts(f AdmissionFacts) AdmissionFacts {
	f.Source.Authority.PublicKey = append([]byte(nil), f.Source.Authority.PublicKey...)
	f.Destination.Authority.PublicKey = append([]byte(nil), f.Destination.Authority.PublicKey...)
	if f.Target != nil {
		target := *f.Target
		f.Target = &target
	}
	return f
}
